apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleofrollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exampleofrollout
  template:
    metadata:
      labels:
        app: exampleofrollout
    spec:
      containers:
      - name: exampleofrollout
        image: nginx:1.27
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
