all:
  hosts:
    node1:
      ansible_host: 10.0.0.51
      ip: 10.0.0.51
      access_ip: 10.0.0.51
    node2:
      ansible_host: 10.0.0.52
      ip: 10.0.0.52
      access_ip: 10.0.0.52
    node3:
      ansible_host: 10.0.0.53
      ip: 10.0.0.53
      access_ip: 10.0.0.53
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
