apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:heads-public-single-node-0-g8aaa828ba
          ports:
            - containerPort: 8428
          volumeMounts:
            - name: victoriametrics-config-volume
              mountPath: /etc/victoriametrics/
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: victoriametrics-config-volume
          configMap:
            name: victoriametrics-config
