apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoriametrics-pv
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  storageClassName: dynamic-sc